### PR TITLE
Scale up disabled feature

### PR DESCRIPTION
**Pull request by radosdesign**
Hi,

I've implemented one tiny feature called "Scale Up disabled", which lets you enable/disable scaling thumbnail up in case thumbnail size is set bigger than original image.
Usually I don't want to scale up a thumbnail as this creates a distortion of the image. I only want to scale it down if necessary. 
Please take a look on it and if you find it useful, feel free to merge it into main repository. Also feel free to contact me with any questions or requests.

Radoslav.

### CODE REVIEW

**Comment by radosdesign** [comment]
I've just noticed that there is an Issue (#85) opened asking for similar feature as the one I've implemented.

**Comment by nioe** [comment]
Any updates on this? Would be very cool if this PR could be merged if there are no other concerns.

**Comment by mwiehl** [comment]
This PR contains a lot of white spaces changes.  A PR should generally address only a single concern; any code re-formatting should be done separately.

**Comment by thiago-negri** [comment]
I'm in need of this feature, but the whitespace changes are unnecessary.

I'll try to extract only the real changes.

**Comment by thiago-negri** [comment]
I've created PR #94 for this and used a positive property "scaleUp" instead of a negative one "scaleUpDisabled".

**Comment by radosdesign** [comment]
Thanks thiago-negri, as I didn't have time to remove unnecessary white spaces, your PR will help the others to use this feature.

**Comment by nqzero** [comment]
for a work-around see https://github.com/coobird/thumbnailator/pull/94#issuecomment-366489245

**Pull request closed without merging**
